### ISSUE TITLE
Default MISP.baseurl should be updated?

### ISSUE THREAD

**Issue by adulau** [MISP/misp-vagrant#1]
Is there a specific reason why 'MISP.baseurl' is `http://127.0.0.1/` instead of `http://127.0.0.1:5000/`?

**Comment by cedricbonhomme** [comment]
Yes, there is a forwarded port mapping:
https://github.com/MISP/misp-vagrant/blob/master/Vagrantfile#L25

Anyway, something is quite strange. This should be transparent for MISP (I've tested that on a certain number of projects...). In the VM MISP is still listening on port 80. Connections from the host on port 5000 are forwarded on port 80 in the VM.

If you do not configure 'MISP.baseurl', just after the vagrant deployment you will see that some links in the main menu of MISP are with the port number (5000), some not (so 80).

I will discuss about that with @iglocska

**Comment by adulau** [comment]
The recent fix from @iglocska will help ;-)

**Comment by cedricbonhomme** [comment]
yes, thanks @iglocska  :-)
